### ISSUE TITLE
Can't run environment on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by zprood** [canonical-web-and-design/cn.ubuntu.com#294]
## Summary

Hello, I just upgrade to 18.04.2 LTS, and merge the latest code from master branch, but there's a error occurred. 
The output log is: https://paste.ubuntu.com/p/BwKMfSqtBv/

## Screenshot
[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/692206/53343464-67e67e00-394b-11e9-8933-ca42b631bbe9.png)

**Comment by pmahnke** [comment]
@zprood are you still having this issue?  please feel free to ping @nottrobin directly for help?

I am going to close it here.
