### ISSUE TITLE
About the need to update Ubuntu Kylin related content on the web page

### ISSUE THREAD

**Issue by fenshezhuiyi** [canonical-web-and-design/cn.ubuntu.com#302]
Hello, I'm Ubuntu Kylin TuoTuo. Since Ubuntu Kylin will release a new version of 19.04 in April, we would like to apply for a new Ubuntu Kylin image [on this page ](https://cn.ubuntu.com/desktop).Hope for approval.
 
new images:[img](http://www.ubuntukylin.com/public/images/dell-xps-laptop-front.png)

**Comment by fenshezhuiyi** [comment]
> Hello, I'm Ubuntu Kylin TuoTuo. Since Ubuntu Kylin will release a new version of 19.04 in April, we would like to apply for a new Ubuntu Kylin image [on this page](https://cn.ubuntu.com/desktop) .Hope for approval.
> 
> new [images:](http://www.ubuntukylin.com/public/images/dell-xps-laptop-front.png)

**Comment by zprood** [comment]
Hi, thanks. I will update in coming update.

**Comment by zprood** [comment]
fixed, close.
