### ISSUE TITLE
Django not finding a template

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/cn.ubuntu.com#312]
[this page](https://cn.ubuntu.com/engage/robot-operating-system-choice-cn) is not being found... can someone look quickly?

**Comment by nottrobin** [comment]
Fixed in https://github.com/canonical-web-and-design/cn.ubuntu.com/pull/314 (also tracked in https://github.com/canonical-web-and-design/cn.ubuntu.com/issues/313)
