### ISSUE TITLE
Related articles redirect to 404s

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/cn.ubuntu.com#321]
Related article is an english article:

https://cn.ubuntu.com/blog/ubuntu-core-18-%e6%ad%a3%e5%bc%8f%e5%8f%91%e5%b8%83%ef%bc%9a%e7%94%a8%e4%ba%8e%e5%ae%89%e5%85%a8%e5%8f%af%e9%9d%a0%e7%9a%84%e7%89%a9%e8%81%94%e7%bd%91%e8%ae%be%e5%a4%87

**Comment by b-m-f** [comment]
Fixed in https://github.com/canonical-web-and-design/cn.ubuntu.com/pull/324 for now.

We need to discuss further, whether related, non-chinese articles should actually redirect to **blog.ubuntu.com** instead of being displayed on the chinese blog
