### ISSUE TITLE
Related Posts heading not translated

### ISSUE THREAD

**Issue by b-m-f** [canonical-web-and-design/cn.ubuntu.com#322]
## Summary

Need chinese translations for english wording
## Screenshot

![image](https://user-images.githubusercontent.com/2843450/56662660-6c55bb80-669c-11e9-9d14-5154bbed9c97.png)

**Comment by zprood** [comment]
Hi Max, I just noticed the front page is un-translated, and the inner title of reading more. I put these three translations here so that you can update. 

1. Latest news from our blog  =  最新博客文章
2. View more from our blog  =  查看更多内容
3. Related posts  =  相关文章

Liam.

**Comment by b-m-f** [comment]
Thanks Liam,

have updated it.
