### ISSUE TITLE
What should related articles display?

### ISSUE THREAD

**Issue by b-m-f** [canonical-web-and-design/cn.ubuntu.com#325]
There are 3 solutions for related articles

## 1
Display all related articles, regardless of language, in the page

## 2
Link to external website for content of another language

## 3
Filter out all non language matching content
This could lead to less related articles being shown. 
Or related articles not being shown unless we overfetch more than we need and then apply filtering.

**Comment by pmahnke** [comment]
I vote for option 3

**Comment by zprood** [comment]
I vote for #3 too.
