### ISSUE TITLE
Pages layouts broken 

### ISSUE THREAD

**Issue by zprood** [canonical-web-and-design/cn.ubuntu.com#331]
## Summary
Hello, I found some page layouts are broken, I guess the css files are missing or doesn't load. 

Effected pages:

- Download page
- Containers
- Server
- Cloud
- Desktop
- Internet-of-things

Screenshots like below: 
## Screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/692206/60888896-55316d80-a28a-11e9-87aa-0ab4e3566455.png)
![image](https://user-images.githubusercontent.com/692206/60888907-5bbfe500-a28a-11e9-92ed-0463b36ee2c4.png)
![image](https://user-images.githubusercontent.com/692206/60888944-75f9c300-a28a-11e9-8292-e621d38ddeae.png)

**Comment by anthonydillon** [comment]
@pmahnke do you mind taking a look at these regressions. My guess is was the Vanilla version bump.

**Comment by pmahnke** [comment]
@deadlight 	did you get anywhere on this?  I think I will just revert

**Comment by anthonydillon** [comment]
@pmahnke @deadlight my guess from the screenshots it's to do with columns not being direct children of rows.

**Comment by zprood** [comment]
Thanks a lot @anthonydillon @pmahnke , I notice the first navigation bar doen't match with top bar, screenshots are below:
English site:
![enu](https://user-images.githubusercontent.com/692206/61021106-a3ea1f00-a3d2-11e9-93cd-d46c0dd90f65.jpg)
China site: 
![cnu](https://user-images.githubusercontent.com/692206/61021108-a64c7900-a3d2-11e9-84cf-5d701f6460e9.jpg)

**Comment by anthonydillon** [comment]
No problem, thanks for reporting the issues. Are you asking for the same drop down navigation style or something else?

**Comment by zprood** [comment]
No, I mean the Ubuntu logo isn't in the same column with Canonical logo.
