### ISSUE TITLE
No blog posts on the main page

### ISSUE THREAD

**Issue by zprood** [canonical-web-and-design/cn.ubuntu.com#338]
## Summary
Hello, I just notice that there're no blogs on the main page, just the "Our latest blog" and "read more" 

## Screenshot

![image](https://user-images.githubusercontent.com/692206/62384867-1d1a0380-b586-11e9-897e-bc7e9f6a5612.png)

**Comment by SirSamTumless** [comment]
@solazio Would you mind taking a look at this?
