### ISSUE TITLE
9 months later will be July,2020 , Jan,2020 is 3 months later.

### ISSUE THREAD

**Issue by lengqing5977** [canonical-web-and-design/cn.ubuntu.com#349]
## Summary

>### Ubuntu Server 19.10
>最新版本Ubuntu Server，拥有9个月安全维护更新，支持到2020年1月。
>
 I count 9 months later will not be Jan,2020 but July,2020.

## Process

Open [https://cn.ubuntu.com/download](https://cn.ubuntu.com/download) and see under 
>## 下载Ubuntu服务器版

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/18274261/67163332-3752c900-f3a0-11e9-9177-aea02ebe2edf.png)

**Comment by zprood** [comment]
Hi, thank you for reporting this issue.
