### ISSUE TITLE
Displaying webpage in Chinese

### ISSUE THREAD

**Issue by gimmebackmysandwich** [canonical-web-and-design/cn.ubuntu.com#353]
## Summary

Hello,
Whenever I open "www.ubuntu.com", it redirects me to "cn.ubuntu.com". I don't live in China. I live in Bangladesh. However, I don't see any option to redirect back to the English website. It should be noted that it happens on all of my devices and on every browser. I did not experience anything like this on other websites. 

It is hoped that you'd help by fixing the problem. Perhaps, enable an option to switch to the English version of the website manually.

**Comment by pmahnke** [comment]
@gimmebackmysandwich thanks for filing, we had an odd redirect that we have fixed.  Out of curiousity, is your browser's language Chinese?
