### ISSUE TITLE
Fix 404s

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/cn.ubuntu.com#365]
After running a linkchecker on the site it seems that we have a bunch of 404s easily fixable on the site: 

https://pastebin.canonical.com/p/GXDVH4Vkyz/

**Comment by pmahnke** [comment]
drangon board download is here - http://cdimage.ubuntu.com/ubuntu-core/18/stable/current/ubuntu-core-18-arm64+snapdragon.img.xz?_ga=2.170431785.863869798.1581351848-558812696.1581351848
