### ISSUE TITLE
Wrong link to canonical.com.

### ISSUE THREAD

**Issue by criwits** [canonical-web-and-design/cn.ubuntu.com#377]
## Summary

(en)The hyper-link in 'About | Ubuntu'(zh-Hans) to Canonical is **wwww.canonical.com**, which is an unreachable link. I think it might be a mistake of www.canonical.com

(cn)在“关于|Ubuntu”页面中指向Canonical官网的链接是“wwww.canonical.com”，此链接不可达（“找不到 wwww.canonical.com 的服务器 IP 地址。”）。这可能是对www.canonical.com的输入错误。

## Process

(en)Just visit https://cn.ubuntu.com/about and find this paragraph:
(cn)只需访问 https://cn.ubuntu.com/about ，找到这一段：

> Ubuntu也是Canonical公司的产品和所有的品牌商标，而科能（上海）软件科技有限公司则是Canonical公司在中国注册的子公司，公司总部位于英国伦敦。

(en)The hyper-link behind 'Canonical'  refers to https://wwww.canonical.com.
(cn)'Canonical'的超链接指向的是 https://wwww.canonical.com 。

## Current and expected result

(en)I think it might be necessary to fix this little bug. Thank you for your time.
(cn)我认为修复这个小bug是有必要的。谢谢。

**Comment by zprood** [comment]
@criwits Hi, thank you for the reporting, the issue has been addressed. We will fix it in next update.
