### ISSUE TITLE
为什么我在ubuntu系统打不开clash的可执行文件

### ISSUE THREAD

**Issue by unknowzsj** [canonical-web-and-design/cn.ubuntu.com#387]
## Summary

[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]
在ubuntu系统中运行可执行文件没有反映，文件是clash，已经勾选了可执行的选项，用命令行打开现实文件不存在，但是我已经装在桌面上了
![2020-04-05 11-13-32屏幕截图](https://user-images.githubusercontent.com/59012336/78465957-9f1e8580-772e-11ea-9b56-ef99273eb788.png)
![2020-04-05 11-14-12屏幕截图](https://user-images.githubusercontent.com/59012336/78465958-a2b20c80-772e-11ea-93cb-ce71f6e50adc.png)

**Comment by zprood** [comment]
请注意，issue只能发网站内容相关的。系统使用相关bug麻烦到launchpad.net报下或者网上搜索下解决方法。谢谢！
