### ISSUE TITLE
Looks like one card is always missing on https://cn.ubuntu.com/blog

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/cn.ubuntu.com#392]
## Summary

The numb of blog cards is odd and it looks like one card is missing

## Possible fix

One option would be add on every blog page a sign-up form as we have on ubuntu.com/blog.

The alternative is to edit the number of posts we are retrieving for the page to be 12 instead of 11. However I am not sure if the blog module can take the number of blogs as an argument or is hardcore to be 11. 

## Screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/40214246/79982441-3cebb180-849e-11ea-9bf3-e86e96b76e0d.png)

**Comment by zprood** [comment]
Besies, the link (internal and external) style is missing too, like the screen below. I think we need to make it more visible. 
![image](https://user-images.githubusercontent.com/692206/80090277-d647c000-8591-11ea-96a0-d9258c063d90.png)
