### ISSUE TITLE
Takeover disappeared 

### ISSUE THREAD

**Issue by zprood** [canonical-web-and-design/cn.ubuntu.com#397]
## Summary

Hi ALL, 
I noticed takeover is disappeared, can you help to check this ?

## Screenshot

[if relevant, include a screenshot]

![image](https://user-images.githubusercontent.com/692206/80445436-d9063480-8946-11ea-820c-8c4035528e48.png)

**Comment by SirSamTumless** [comment]
We can't replicate this bug on our side, although we'll investigate it to see if we can find more.

**Comment by zprood** [comment]
Hi, I re-test it on my computer and asked some users to test, they all have this issue with Chrome, so as mine. But the takeover works well under firefox. 

Here are errors I got from Chrome. 
Uncaught TypeError: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.
    at (index):364

latest-news.js?v=d1d78ae:1 Error "TypeError: Cannot read property '0' of undefined" occured when trying to fetch the latest spotlight article from the API

**Comment by zprood** [comment]
I think I found the problem, it relates about local language, 
<section lang="en" data-lang="en_GB" class="p-takeover--grad js-takeover">
I have set Firefox with English, then takeover appeared,  changed to Chinese, then no takeover.

**Comment by deadlight** [comment]
@zprood ah, that's what I was about to check. It should be a simple task to fix this and I'll make sure to include switching languages in our QA to catch these issues in future.

**Comment by zprood** [comment]
Thanks a lot, no worries.
