### ISSUE TITLE
Setup Perkuto

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/cn.ubuntu.com#415]

**Comment by steverydz** [comment]
Is there more information on what this involves?

**Comment by zprood** [comment]
Lucia has done the marketo side, and waiting for web team to integrate.

**Comment by steverydz** [comment]
@zprood thanks - looks like this card isn't necessary then as https://github.com/canonical-web-and-design/cn.ubuntu.com/issues/414 will take care of the integratoin

**Comment by pmahnke** [comment]
I don't think the perkuto side was done.  Also, I thought we were doing a single newsletter as there isn't that much blog content, not all the same topics as in the UK one?

**Comment by pmahnke** [comment]
In fact, the marketo form only has the email address, no checkboxes.  @zprood ?

**Comment by zprood** [comment]
I see there's no checkboxed, do I need to add the 4 checkboxed like the form on page? If yes, I can add soon. Sorry, missed the form configuration part.

**Comment by pmahnke** [comment]
This is still not done, reopening.

**Comment by pmahnke** [comment]
I have set it up, but the test hasn't arrived to confirm.
