### ISSUE TITLE
login twice

### ISSUE THREAD

**Issue by wuaoya** [canonical-web-and-design/cn.ubuntu.com#465]
## Summary

[please describe the issue]

## Process

[After installation]

## Current and expected result

[why I need to input the user name and password twice for the first login]

## Screenshot

[if relevant, include a screenshot]
![捕获](https://user-images.githubusercontent.com/45376267/101018696-d3409380-35a6-11eb-97a7-65f3bd3bb7b2.PNG)

**Comment by zprood** [comment]
Hi, the repo is for cn.ubuntu.com website maintenance not for ubuntu technical issue tracking. Please report on launchpad.net or get help from askubuntu.com. We need to close it.
