### ISSUE TITLE
bug in page https://cn.ubuntu.com/download

### ISSUE THREAD

**Issue by dendi6666** [canonical-web-and-design/cn.ubuntu.com#469]
## Summary
The URL of the download button starts with HTTP in https://cn.ubuntu.com/download page.
But the website protocol is HTTPS.
Causes the download button to be invalid
## Process
1.open page  https://cn.ubuntu.com/download page.
2.click frist download button "下载"
3.Causes the download button to be invalid and Console printing error message ：“Mixed Content: The site at 'https://cn.ubuntu.com/' was loaded over a secure connection, but the file at 'http://releases.ubuntu.com/20.04/ubuntu-20.04.1-desktop-amd64.iso' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.”
[list the steps to replicate the issue]
The download button works

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to file this issue. A fix has been proposed and will be rolled out soon.
