### ISSUE TITLE
cn.ubuntu.com system download return 404 error

### ISSUE THREAD

**Issue by TPCW-DRW-TP211** [canonical-web-and-design/cn.ubuntu.com#487]
## Summary

cn.ubuntu.com website system download 404

## Process

Ubuntu 20.04.2 Desktop
cn.ubuntu.com

## Current and expected result

Ubuntu Desktop 20.04.2 LTS iso file name does not match
The file name should be *20.04.2* instead of *20.04.2.0*

## Screenshot

![QQ截图20210217020623](https://user-images.githubusercontent.com/25274820/108103864-7a709980-70c5-11eb-93c5-9539d5863c88.png)
![QQ截图20210217020724](https://user-images.githubusercontent.com/25274820/108103902-89efe280-70c5-11eb-9513-800b4acc5145.png)
![QQ截图20210217021017](https://user-images.githubusercontent.com/25274820/108103925-91af8700-70c5-11eb-9b2b-55668d7f169d.png)

**Comment by zprood** [comment]
Fixed, please check https://cn.ubuntu.com/download again. 
Thanks.
