### ISSUE TITLE
Ubuntu 20.04.2 LTS （笔记本电脑）鼠标左键失效的问题

### ISSUE THREAD

**Issue by szoliver** [canonical-web-and-design/cn.ubuntu.com#495]
## Summary

Ubuntu 20.04.2 LTS 笔记本电脑不关机的情况下合上笔记本后很长时间，再次打开笔记本鼠标左键失效，右键正常，此问题多次出现，我有一个习惯，开发程序工作完成后不关闭IDE，不关闭笔记本电脑，只是直接合上笔记本，第二天或是第三天再次打开笔记本时，触摸键盘鼠标只能使用右键，接上USB鼠标也是一样。只有重启后鼠标才正常。
最近才更新到20.04版本，为了保持开发工具的稳定性，没有直接升级到Ubuntu最新版本，只升级到LTS版本。升级前的旧版本系统从来没有这样的问题出现。

## Process

1.打开工作软件工作，本人用得最多的是vscode，但个人认为跟使用的软件没有太大关系；
2.直接合上笔记本，第二天再次打开笔记本工作，此时会发现鼠标左键失效，右键正常；
3.重启笔记本电脑且一切正常；
本人猜测：合上笔记本后系统进入休眠状态，跟鼠标相关的驱动或服务工作状态异常导致左键失效，重启后驱动或服务正常重启。

## Current and expected result

不管是否从待机、休眠状态中恢复，鼠标左键和右键都应能正常使用。

## Screenshot

不适合截图

**Comment by zprood** [comment]
你好，此项目仅适用于Ubuntu中文网站维护更新。Ubuntu系统使用相关问题，麻烦到askubuntu.com提问或者launchpad.net报下bug。谢谢！issue先关闭了。
