### ISSUE TITLE
bug...libpcap

### ISSUE THREAD

**Issue by libxengine** [canonical-web-and-design/cn.ubuntu.com#511]
sudo apt install libpcap-dev
on ubuntu 20.04.2
when i use funtcion pcap_findalldevs_ex  tip to me undefined reference to `pcap_findalldevs_ex'

the library can be use pcap_findalldevs .can't use pcap_findalldevs_ex

**Comment by zprood** [comment]
Hi, it seems that this is a library issue, please report the issue on launchpad: https://bugs.launchpad.net/ubuntu/+source/libpcap
