### ISSUE TITLE
Selection area error on Desktop

### ISSUE THREAD

**Issue by reeqoo** [canonical-web-and-design/cn.ubuntu.com#526]
## Summary

When use mouse draw a range for selection, the selection range will be given a shift. The Current Ubuntu version is "21.04 (Hirsute Hippo)" and it's upgrade from 20.10 use software updater in GUI.

## Process

Just simply draw a selection range on Desktop.

## Current and expected result

The size and position should same as mouse_down and mouse_release.

## Screenshot

![DesktopSelectRangeBug](https://user-images.githubusercontent.com/23308312/118401215-6114c480-b697-11eb-83df-e9ead082a3d4.png)

**Comment by anthonydillon** [comment]
@reeqoo sorry to hear you are having a problem with your selection region. Unfortunately, I cannot provide support via this channel as this is the bug list for the website.

If you could report a bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question as a topic on https://discourse.ubuntu.com/c/support-help-requests and you should receive a quick response.
