### ISSUE TITLE
need developer kits containing in server's ISO

### ISSUE THREAD

**Issue by Tancen** [canonical-web-and-design/cn.ubuntu.com#528]
Ubuntu 20.04.2 LTS server's ISO doesn't support recent ethernet network drives, if the machine's network hardware is recent, it can't be connected to the internet. So, it can only the way of download the hardware drives by other machine and copy it in the machine to make it work. But, when you do compile the drives, you will discover that it requires 'make, GCC ...'. So sad!

**Comment by zprood** [comment]
Hi, this project is for website content only, if you have a network or other system issues, please report them on the [launchpad.net](url), Thanks.
