### ISSUE TITLE
iot install ubuntu stuck

### ISSUE THREAD

**Issue by liang-jin-hua** [canonical-web-and-design/cn.ubuntu.com#553]
## Summary
when I install ubuntu,it is struck. you check the Screenshot.
## Process
Use ubuntu-18.04.4-live-server-amd64.iso to make a USB boot disk，then use the boot disk install Ubuntu
## Current and expected result
I added console=ttyS0,115200n8 in the grub interface， then press "Ctrl - x",but it got stuck and didn't go down.
Why does it get stuck and what to do next.
## Screenshot
![image](https://user-images.githubusercontent.com/56709134/129650172-605b31f1-a689-4ab7-b9d6-e8a73da13ba6.png)

**Comment by zprood** [comment]
It's not the website issue. If you have an Ubuntu installation problem, please visit askubuntu.com or launchpad.
