### ISSUE TITLE
Mac系统在iterm2软件使用sz命令时出现\udc8a: command not found 的错误提示

### ISSUE THREAD

**Issue by MF-ReStart** [canonical-web-and-design/cn.ubuntu.com#574]
## Mac系统在iterm2软件使用sz命令时出现\udc8a: command not found 的错误提示

[please describe the issue]
1.我在Mac系统上使用iterm2这个终端连接工具，我配置了Mac系统使用sz rz的脚本，我是按照这个教程配置的（https://github.com/snow-sprite/rzsz），我的配置没有问题，我能成功使用sz rz上传下载文件，但是它显示了\udc8a: command not found这个错误提示，这让我很不爽。

## Current and expected result

我在Ubuntu20.04.2 TLS版本的系统上，是没有\udc8a: command not found这个错误提示的，但是在20.04.3 TLS这个版本系统上会有这个错误提示，我不想看到这个烦人的错误，我猜测是utf-8字符不能解码\udc8a字符集造成的

## Screenshot

这个是20.04.3 TLS版本系统使用sz命令下载文件到本地的错误提示截图
![](https://hercules-gitbook-image.oss-cn-shenzhen.aliyuncs.com/bug/Xnip2021-12-23_09-35-04.png)

但是20.04.2 TLS版本系统同样的使用sz命令却没有这个错误提示
![](https://hercules-gitbook-image.oss-cn-shenzhen.aliyuncs.com/bug/Xnip2021-12-23_09-36-04.png)
## last

其实sz命令是能成功下载文件到本地的，但是这个错误提示让我很不爽

**Comment by zprood** [comment]
你好，此repo只是针对Ubuntu中文网站和网站内容。关于Ubuntu系统本身的问题和bug，请到 launchpad.net 查看和提交。
谢谢！
