### ISSUE TITLE
北京办公室的地址的邮编是错的

### ISSUE THREAD

**Issue by xiaopangju** [canonical-web-and-design/cn.ubuntu.com#623]
## Summary

在[联系我们](https://cn.ubuntu.com/contact)页面的底部，有北京办公室的地址和邮编。页面上显示邮编为100004，实际为100020

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

![image](https://user-images.githubusercontent.com/56964531/165937560-f9bdacfa-7af6-41d9-851c-aa6caada1772.png)

**Comment by sowasred2012** [comment]
@zprood are you able to help with this one?

**Comment by zprood** [comment]
> @zprood are you able to help with this one?
Yes, will do.

**Comment by zprood** [comment]
> ## Summary
> 在[联系我们](https://cn.ubuntu.com/contact)页面的底部，有北京办公室的地址和邮编。页面上显示邮编为100004，实际为100020
> 
> ## Process
> [list the steps to replicate the issue]
> 
> ## Current and expected result
> [describe what happened and what you expected]
> 
> ## Screenshot
> ![image](https://user-images.githubusercontent.com/56964531/165937560-f9bdacfa-7af6-41d9-851c-aa6caada1772.png)

Thank you for the feedback, updated with new PR.
